// Wallpapers are generated by scripts/optimize-assets.mjs as
// `name.webp` (2560w), `name-1280.webp` and `name-thumb.webp` (400w).

/** Pick the smallest wallpaper variant that still covers the screen. */
export const wallpaperSrc = (path: string): string => {
  const needed = window.screen.width * (window.devicePixelRatio || 1);
  return needed <= 1440 ? path.replace(/\.webp$/, "-1280.webp") : path;
};

/** Small preview used by pickers and tiny tiles. */
export const wallpaperThumb = (path: string): string =>
  path.replace(/\.webp$/, "-thumb.webp");
